
pvc:
  storage: "1Gi"

job:
  image: "ludenus/junit-runner"
  version: "0.0.4-master-1853332-SNAPSHOT"
  env:
    DEBUG_SLEEP_BEFORE_EXIT_SECONDS: 600
    SUBMIT_ALLURE_REPORT: true

deployment:
  replicaCount: 1
  image: "kochetkovma/allure-server"
  version: "2.8.3"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
  containerPort: 8080
  livenessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
service:
  type: ClusterIP
#  loadBalancerIP: "123.123.123.123"
  port: 80
