apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-allure-server"
  labels:
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}"
spec:
  type: "{{ .Values.service.type }}"
  {{- if eq "LoadBalancer" .Values.service.type }}
  {{- if kindIs "string" .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{- end }}
  selector:
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}"
  ports:
    - name: "http"
      protocol: TCP
      port: {{  .Values.deployment.containerPort }}
      targetPort: {{  .Values.deployment.containerPort }}




